In [1]:
import numpy as np
import pandas as pd

In [21]:
df1 = pd.read_csv("2016_tomato_Env-Info_Daily.csv", encoding='cp949')
df2 = pd.read_csv("2017_tomato_Env-Info_Daily.csv", encoding='cp949')

In [22]:
df1.head()

수집일  내부CO2(ppm)  내부습도(%)  외부온도(도)  내부온도(도)
0  2017-01-01      380.00    90.04     1.46    16.83
1  2017-01-02      378.46    90.96     2.67    16.79
2  2017-01-03      379.50    92.54     6.33    17.25
3  2017-01-04      380.00    91.63     4.00    17.00
4  2017-01-05      373.21    90.42     3.75    16.54

In [23]:
df2.head()

수집일  내부CO2(ppm)  내부습도(%)  외부온도(도)  내부온도(도)
0  2017-12-11      792.38    92.71     0.38    11.67
1  2017-12-12      836.67    85.42    -3.17    12.00
2  2017-12-13      899.13    79.42    -3.25    13.42
3  2017-12-14     1051.46    81.04    -3.92    14.67
4  2017-12-15     1461.25    85.96    -1.42    17.88

In [24]:
df1.isnull().sum()

수집일           0
내부CO2(ppm)    0
내부습도(%)       0
외부온도(도)       0
내부온도(도)       0
dtype: int64

In [25]:
df2.isnull().sum()

수집일           0
내부CO2(ppm)    0
내부습도(%)       0
외부온도(도)       0
내부온도(도)       0
dtype: int64

In [26]:
df1['내부질소(t ha-1)'] = 0
df1['내부인(t ha-1)'] = 0
df1['생장길이(cm)'] = 0
df1['열매수'] = 0

df2['내부질소(t ha-1)'] = 0
df2['내부인(t ha-1)'] = 0
df2['생장길이(cm)'] = 0
df2['열매수'] = 0

In [27]:
gr1=pd.read_csv("2016_tomato_Growing-Info_Daily.csv", encoding='UTF8')
gr2=pd.read_csv("2017_tomato_Growing-Info_Daily.csv", encoding='UTF8')

In [28]:
gr1.head()

조사일  생장길이(cm)  열매수(개)
0  2017-03-05       0.0    13.0
1  2017-03-12     193.0    13.0
2  2017-03-19     190.0    13.0
3  2017-03-26     178.0    19.0
4  2017-04-02     168.0    13.0

In [29]:
gr2.head()

조사일  생장길이(cm)  열매수(개)
0  2017-12-24     393.0     0.0
1  2017-12-31      63.0     0.0
2  2018-01-07      38.0     0.0
3  2018-01-14      54.0     4.0
4  2018-01-21      75.0     8.0

In [30]:
cur_idx=0
for index, row in df1.iterrows():
    if row['수집일'] == gr1.iloc[cur_idx, 0]:
        df1.iloc[index, 7] = gr1.iloc[cur_idx, 1]
        cur_idx += 1

In [31]:
df1["생장길이(cm)"].unique()

array([   0,  193,  190,  178,  168, 2624,  220, 2861,  148,  200,  260],
      dtype=int64)

In [32]:
cur_idx=0
for index, row in df1.iterrows():
    if row['수집일'] == gr1.iloc[cur_idx, 0]:
        df1.iloc[index, 8] = gr1.iloc[cur_idx, 2]
        cur_idx += 1

In [33]:
df1["열매수"].unique()

array([ 0, 13, 19, 16, 14, 17, 15, 18], dtype=int64)

In [34]:
cur_idx=0
for index, row in df2.iterrows():
    if row['수집일'] == gr2.iloc[cur_idx, 0]:
        df2.iloc[index, 7] = gr2.iloc[cur_idx, 1]
        cur_idx += 1

IndexError: index 12 is out of bounds for axis 0 with size 12

In [35]:
df2["생장길이(cm)"].unique()

array([  0, 393,  63,  38,  54,  75, 125,  84,  55, 115, 119, 113, 164],
      dtype=int64)

In [36]:
cur_idx=0
for index, row in df2.iterrows():
    if row['수집일'] == gr2.iloc[cur_idx, 0]:
        df2.iloc[index, 8] = gr2.iloc[cur_idx, 1]
        cur_idx += 1

IndexError: index 12 is out of bounds for axis 0 with size 12

In [37]:
df2["열매수"].unique()

array([  0, 393,  63,  38,  54,  75, 125,  84,  55, 115, 119, 113, 164],
      dtype=int64)

In [65]:
df = pd.read_csv("prepare/data3.csv", encoding='cp949')

In [66]:
df.head()

Unnamed: 0         수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  \
0           0  2018-07-21      421.63    78.46        297.50    29.08   
1           1  2018-07-22      410.08    70.58        284.00    30.13   
2           2  2018-07-23      381.33    71.17        314.92    29.67   
3           3  2018-07-24      380.54    76.58        320.33    29.75   
4           4  2018-07-25      372.25    78.83        249.04    28.96   

   내부온도(도)  내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0    30.46             0            0         0    0  
1    31.58             0            0         0    0  
2    31.29             0            0         0    0  
3    31.17             0            0         0    0  
4    30.50             0            0         0    0

In [67]:
cur_idx=0
for index, row in df.iterrows():
    if row['생장길이(cm)'] == 0 or row['열매수'] == 0:
        df.drop(index, inplace=True, axis=0)
    else :
        cur_idx += 1

In [68]:
df.head()

Unnamed: 0         수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  \
85           85  2018-10-14      389.00    90.92        215.63    12.33   
87           87  2018-10-16      403.33    94.00        109.38    13.17   
158         158  2018-12-26      419.04    83.96        124.04     2.54   
171         171  2019-01-08      452.67    87.42        109.92    -0.92   
178         178  2019-01-15      430.88    91.50         87.83     0.79   

     내부온도(도)  내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
85     17.92             0            0      3063  101  
87     17.33             0            0      3063  101  
158    17.13             0            0       903    7  
171    15.54             0            0       328   20  
178    15.71             0            0       177   31

In [69]:
df.reset_index(inplace=True)

In [70]:
df.head()

index  Unnamed: 0         수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  \
0     85          85  2018-10-14      389.00    90.92        215.63    12.33   
1     87          87  2018-10-16      403.33    94.00        109.38    13.17   
2    158         158  2018-12-26      419.04    83.96        124.04     2.54   
3    171         171  2019-01-08      452.67    87.42        109.92    -0.92   
4    178         178  2019-01-15      430.88    91.50         87.83     0.79   

   내부온도(도)  내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0    17.92             0            0      3063  101  
1    17.33             0            0      3063  101  
2    17.13             0            0       903    7  
3    15.54             0            0       328   20  
4    15.71             0            0       177   31

In [71]:
df.drop(['Unnamed: 0', 'index'], inplace=True, axis=1)

In [72]:
df.head()

수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  내부온도(도)  \
0  2018-10-14      389.00    90.92        215.63    12.33    17.92   
1  2018-10-16      403.33    94.00        109.38    13.17    17.33   
2  2018-12-26      419.04    83.96        124.04     2.54    17.13   
3  2019-01-08      452.67    87.42        109.92    -0.92    15.54   
4  2019-01-15      430.88    91.50         87.83     0.79    15.71   

   내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0             0            0      3063  101  
1             0            0      3063  101  
2             0            0       903    7  
3             0            0       328   20  
4             0            0       177   31

In [73]:
df

수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  내부온도(도)  \
0   2018-10-14      389.00    90.92        215.63    12.33    17.92   
1   2018-10-16      403.33    94.00        109.38    13.17    17.33   
2   2018-12-26      419.04    83.96        124.04     2.54    17.13   
3   2019-01-08      452.67    87.42        109.92    -0.92    15.54   
4   2019-01-15      430.88    91.50         87.83     0.79    15.71   
..         ...         ...      ...           ...      ...      ...   
61  2022-05-04      582.21    78.79         22.43    15.43    17.54   
62  2022-05-11      672.13    94.79        196.13    18.29    20.17   
63  2022-05-18      621.50    89.08        303.75    20.33    21.13   
64  2022-05-25      621.25    98.63        294.88    21.46    22.42   
65  2022-06-08      529.25    99.92        138.71    17.67    18.92   

    내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0              0            0      3063  101  
1              0            0      3063  101  
2              0            0       903    7  
3              0            0       328   20  
4              0            0       177   31  
..           ...          ...       ...  ...  
61             0            0       243   13  
62             0            0       268   16  
63             0            0       204   14  
64             0            0       244   13  
65             0            0       193   11  

[66 rows x 10 columns]

In [74]:
cur_idx=0
for index, row in df1.iterrows():
    if row['생장길이(cm)'] == 0 or row['열매수'] == 0:
        df1.drop(index, inplace=True, axis=0)
    else :
        cur_idx += 1

In [75]:
df1

수집일  내부CO2(ppm)  내부습도(%)  외부온도(도)  내부온도(도)  내부질소(t ha-1)  \
70   2017-03-12      380.00    88.63     6.96    17.96             0   
77   2017-03-19      379.46    93.13     7.88    17.92             0   
84   2017-03-26      378.96    96.83     7.13    15.96             0   
91   2017-04-02      380.00    93.79     8.54    18.00             0   
98   2017-04-09      380.00    87.54    16.29    20.71             0   
105  2017-04-16      380.00    84.46    18.75    22.42             0   
112  2017-04-23      380.00    88.92    13.00    19.58             0   
119  2017-04-30      380.00    80.58    18.33    21.83             0   
126  2017-05-07      380.00    83.00    18.63    21.63             0   
133  2017-05-14      380.00    87.58    18.71    21.33             0   
140  2017-05-21      380.00    88.54    20.58    23.21             0   

     내부인(t ha-1)  생장길이(cm)  열매수  
70             0       193   13  
77             0       190   13  
84             0       178   19  
91             0       168   13  
98             0      2624   19  
105            0       220   16  
112            0      2861   14  
119            0       148   17  
126            0       200   15  
133            0       260   18  
140            0       200   17

In [76]:
cur_idx=0
for index, row in df2.iterrows():
    if row['생장길이(cm)'] == 0 or row['열매수'] == 0:
        df2.drop(index, inplace=True, axis=0)
    else :
        cur_idx += 1

In [77]:
df2

수집일  내부CO2(ppm)  내부습도(%)  외부온도(도)  내부온도(도)  내부질소(t ha-1)  \
13  2017-12-24      711.33    99.75     6.79    16.29             0   
20  2017-12-31      655.67    74.33     3.63    15.13             0   
27  2018-01-07      925.71    80.33     0.83    14.96             0   
34  2018-01-14      950.13    75.33    -0.88    16.25             0   
41  2018-01-21      827.42    77.08     0.83    14.75             0   
48  2018-01-28      664.71    82.83    -1.00    16.29             0   
55  2018-02-04      666.88    89.17    -5.38    15.75             0   
62  2018-02-11      681.42    92.25    -2.17    14.38             0   
69  2018-02-18      660.67    90.25     1.83    14.88             0   
76  2018-02-25      658.38    88.83     5.04    16.29             0   
83  2018-03-04      712.83    91.75    12.58    16.83             0   
90  2018-03-11      782.54    78.50     5.13    16.54             0   

    내부인(t ha-1)  생장길이(cm)  열매수  
13            0       393  393  
20            0        63   63  
27            0        38   38  
34            0        54   54  
41            0        75   75  
48            0       125  125  
55            0        84   84  
62            0        55   55  
69            0       115  115  
76            0       119  119  
83            0       113  113  
90            0       164  164

In [78]:
df = pd.concat([df, df1, df2], axis=0)

In [79]:
df

수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  내부온도(도)  \
0   2018-10-14      389.00    90.92        215.63    12.33    17.92   
1   2018-10-16      403.33    94.00        109.38    13.17    17.33   
2   2018-12-26      419.04    83.96        124.04     2.54    17.13   
3   2019-01-08      452.67    87.42        109.92    -0.92    15.54   
4   2019-01-15      430.88    91.50         87.83     0.79    15.71   
..         ...         ...      ...           ...      ...      ...   
62  2018-02-11      681.42    92.25           NaN    -2.17    14.38   
69  2018-02-18      660.67    90.25           NaN     1.83    14.88   
76  2018-02-25      658.38    88.83           NaN     5.04    16.29   
83  2018-03-04      712.83    91.75           NaN    12.58    16.83   
90  2018-03-11      782.54    78.50           NaN     5.13    16.54   

    내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0              0            0      3063  101  
1              0            0      3063  101  
2              0            0       903    7  
3              0            0       328   20  
4              0            0       177   31  
..           ...          ...       ...  ...  
62             0            0        55   55  
69             0            0       115  115  
76             0            0       119  119  
83             0            0       113  113  
90             0            0       164  164  

[89 rows x 10 columns]

In [80]:
df.reset_index(inplace=True)

In [81]:
df

index         수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  내부온도(도)  \
0       0  2018-10-14      389.00    90.92        215.63    12.33    17.92   
1       1  2018-10-16      403.33    94.00        109.38    13.17    17.33   
2       2  2018-12-26      419.04    83.96        124.04     2.54    17.13   
3       3  2019-01-08      452.67    87.42        109.92    -0.92    15.54   
4       4  2019-01-15      430.88    91.50         87.83     0.79    15.71   
..    ...         ...         ...      ...           ...      ...      ...   
84     62  2018-02-11      681.42    92.25           NaN    -2.17    14.38   
85     69  2018-02-18      660.67    90.25           NaN     1.83    14.88   
86     76  2018-02-25      658.38    88.83           NaN     5.04    16.29   
87     83  2018-03-04      712.83    91.75           NaN    12.58    16.83   
88     90  2018-03-11      782.54    78.50           NaN     5.13    16.54   

    내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0              0            0      3063  101  
1              0            0      3063  101  
2              0            0       903    7  
3              0            0       328   20  
4              0            0       177   31  
..           ...          ...       ...  ...  
84             0            0        55   55  
85             0            0       115  115  
86             0            0       119  119  
87             0            0       113  113  
88             0            0       164  164  

[89 rows x 11 columns]

In [82]:
df.drop(['index'], inplace=True, axis=1)

In [83]:
df

수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  내부온도(도)  \
0   2018-10-14      389.00    90.92        215.63    12.33    17.92   
1   2018-10-16      403.33    94.00        109.38    13.17    17.33   
2   2018-12-26      419.04    83.96        124.04     2.54    17.13   
3   2019-01-08      452.67    87.42        109.92    -0.92    15.54   
4   2019-01-15      430.88    91.50         87.83     0.79    15.71   
..         ...         ...      ...           ...      ...      ...   
84  2018-02-11      681.42    92.25           NaN    -2.17    14.38   
85  2018-02-18      660.67    90.25           NaN     1.83    14.88   
86  2018-02-25      658.38    88.83           NaN     5.04    16.29   
87  2018-03-04      712.83    91.75           NaN    12.58    16.83   
88  2018-03-11      782.54    78.50           NaN     5.13    16.54   

    내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0              0            0      3063  101  
1              0            0      3063  101  
2              0            0       903    7  
3              0            0       328   20  
4              0            0       177   31  
..           ...          ...       ...  ...  
84             0            0        55   55  
85             0            0       115  115  
86             0            0       119  119  
87             0            0       113  113  
88             0            0       164  164  

[89 rows x 10 columns]

In [85]:
df.to_csv("C:\\Users\\user\\Desktop\\MicroFarm2\\MicroFarm\\Data\\Tomato\\prepare\\data4.csv")