In [1]:
import numpy as np
import pandas as pd

In [25]:
df = pd.read_csv("./data2.csv")
df.head()

Unnamed: 0         수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  \
0           0  2018-07-21      421.63    78.46        297.50    29.08   
1           1  2018-07-22      410.08    70.58        284.00    30.13   
2           2  2018-07-23      381.33    71.17        314.92    29.67   
3           3  2018-07-24      380.54    76.58        320.33    29.75   
4           4  2018-07-25      372.25    78.83        249.04    28.96   

   내부온도(도)  내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0    30.46             0            0         0    0  
1    31.58             0            0         0    0  
2    31.29             0            0         0    0  
3    31.17             0            0         0    0  
4    30.50             0            0         0    0

In [26]:
df.drop(['Unnamed: 0'], axis = 1, inplace=True)

In [27]:
df.head()

수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  내부온도(도)  \
0  2018-07-21      421.63    78.46        297.50    29.08    30.46   
1  2018-07-22      410.08    70.58        284.00    30.13    31.58   
2  2018-07-23      381.33    71.17        314.92    29.67    31.29   
3  2018-07-24      380.54    76.58        320.33    29.75    31.17   
4  2018-07-25      372.25    78.83        249.04    28.96    30.50   

   내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0             0            0         0    0  
1             0            0         0    0  
2             0            0         0    0  
3             0            0         0    0  
4             0            0         0    0

In [28]:
gf1 = pd.read_csv("./2018_tomato_Growing-Info_Daily.csv")
gf2 = pd.read_csv("./2019_tomato_Growing-Info_Daily.csv")
gf3 = pd.read_csv("./2020_tomato_Growing-Info_Daily.csv")
gf4 = pd.read_csv("./2021_tomato_Growing-Info_Daily.csv")
gf5 = pd.read_csv("./2022_tomato_Growing-Info_Daily.csv")

In [29]:
gf1.head()

조사일  주차  생장길이(cm)  화방높이(cm)  줄기굵기(mm)  엽장(cm)  엽폭(cm)  엽수(개)  \
0  2018-10-14  13    3063.0       0.0       7.0   313.0   260.0   31.0   
1  2018-10-16  13    3063.0       0.0       7.0   313.0   260.0   31.0   
2  2018-10-23  14       0.0       0.0       7.0   360.0   303.0   22.0   
3  2018-10-30  15       0.0       0.0       0.0   343.0   280.0   17.0   
4  2018-11-06  16       0.0       0.0       8.0   335.0   335.0   13.0   

   개화군(점)  착과군(점)  열매수(개)  최종화방번호(번)  
0     8.0     9.0   101.0        NaN  
1     8.0     9.0   101.0        NaN  
2     3.0     3.0   112.0        NaN  
3     0.0     0.0   105.0        NaN  
4     0.0     0.0    97.0        NaN

In [30]:
gf1['생장길이(cm)'].unique()

array([3063.,    0.,  188.,  310.,  543.,  691.,  903.,  328.,  177.,
        173.,  225.,  240.,  246.,  238.,  281.,  318.,  267.,  288.,
        241.,  289.,  255.])

In [11]:
df['생장길이(cm)'] = 0

In [31]:
cur_idx = 0
for index, row in df.iterrows():
    if row['수집일'] == gf1.iloc[cur_idx, 0]:
        df.iloc[index, 8] = gf1.iloc[cur_idx, 2]
        cur_idx += 1

In [32]:
df['생장길이(cm)'].unique()

array([   0, 3063,  188,  310,  543,  691,  903,  328,  177,  173,  225,
        240,  246,  238,  281,  318,  267,  288,  241,  289,  255,   98,
        139,   59,   36,   28, 3124,  125,  230,  198,  167,  192,  190,
        212,  175,  204,  213,  209,  193,  174,  202,  239,   86,   75],
      dtype=int64)

In [33]:
cur_idx = 0
for index, row in df.iterrows():
    if row['수집일'] == gf2.iloc[cur_idx, 0]:
        df.iloc[index, 8] = gf2.iloc[cur_idx, 2]
        cur_idx += 1

cur_idx = 0
for index, row in df.iterrows():
    if row['수집일'] == gf3.iloc[cur_idx, 0]:
        df.iloc[index, 8] = gf3.iloc[cur_idx, 2]
        cur_idx += 1
    

IndexError: index 26 is out of bounds for axis 0 with size 26

In [34]:
cur_idx = 0
for index, row in df.iterrows():
    if row['수집일'] == gf4.iloc[cur_idx, 0]:
        df.iloc[index, 8] = gf4.iloc[cur_idx, 2]
        cur_idx += 1

IndexError: index 18 is out of bounds for axis 0 with size 18

In [35]:
cur_idx = 0
for index, row in df.iterrows():
    if row['수집일'] == gf5.iloc[cur_idx, 0]:
        df.iloc[index, 8] = gf5.iloc[cur_idx, 2]
        cur_idx += 1

In [36]:
df['생장길이(cm)'].unique()

array([   0, 3063,  188,  310,  543,  691,  903,  328,  177,  173,  225,
        240,  246,  238,  281,  318,  267,  288,  241,  289,  255,   98,
        139,   59,   36,   28, 3124,  125,  230,  198,  167,  192,  190,
         85,  131,  212,  103,  175,  204,  124,  213,  161,  105,  193,
        130,  133,  150,  202,  185,  110,  239,   18,   86,   13,   75,
         20,  316,  262,  243,  268,  244], dtype=int64)

In [18]:
df.columns

Index(['수집일', '내부CO2(ppm)', '내부습도(%)', '일사량(W/m-2·s)', '외부온도(도)', '내부온도(도)',
       '열매수', '내부질소(t ha-1)', '내부인(t ha-1)', '생장길이(cm)'],
      dtype='object')

In [19]:
df = df[['수집일', '내부CO2(ppm)', '내부습도(%)', '일사량(W/m-2·s)', '외부온도(도)', '내부온도(도)',
       '내부질소(t ha-1)', '내부인(t ha-1)', '생장길이(cm)', '열매수']]

In [20]:
df.head()

수집일  내부CO2(ppm)  내부습도(%)  일사량(W/m-2·s)  외부온도(도)  내부온도(도)  \
0  2018-07-21      421.63    78.46        297.50    29.08    30.46   
1  2018-07-22      410.08    70.58        284.00    30.13    31.58   
2  2018-07-23      381.33    71.17        314.92    29.67    31.29   
3  2018-07-24      380.54    76.58        320.33    29.75    31.17   
4  2018-07-25      372.25    78.83        249.04    28.96    30.50   

   내부질소(t ha-1)  내부인(t ha-1)  생장길이(cm)  열매수  
0             0            0         0    0  
1             0            0         0    0  
2             0            0         0    0  
3             0            0         0    0  
4             0            0         0    0

In [37]:
df['열매수'].unique()

array([  0, 101, 112, 105,  97,  83,  62,   7,  20,  31,  45,  61, 116,
       130, 157, 169, 163, 127, 149, 134, 126, 117,  74,  92,  69,   6,
        11,  14,  16,  17,  13,  10,  12,   3,  15,  25,  36,  47,  50,
        68,  65,  89,  76,  82,   9], dtype=int64)

In [38]:
df.to_csv("./data3.csv")